export const adminActionType ={

    
    ADMIN_LOGIN_REQUEST : "ADMIN_LOGIN_REQUEST",
    ADMIN_LOGIN_SUCCESS : "ADMIN_LOGIN_SUCCESS",
    ADMIN_LOGIN_FAIL : "ADMIN_LOGIN_FAIL",
    ADMIN_LOGOUT : "ADMIN_LOGOUT",
    
    ADMIN_USER_FETCH_REQUEST : "ADMIN_USER_FETCH_REQUEST",
    ADMIN_USER_FETCH_SUCCESS : "ADMIN_USER_FETCH_SUCCESS",
    ADMIN_USER_FETCH_FAIL : "ADMIN_USER_FETCH_FAIL",
    
    ADMIN_BIKE_ADD_REQUEST : "ADMIN_BIKE_ADD_REQUEST",
    ADMIN_BIKE_ADD_SUCCESS : "ADMIN_BIKE_ADD_SUCCESS",
    ADMIN_BIKE_ADD_FAIL : "ADMIN_BIKE_ADD_FAIL"
}