export const adminActionType ={

    
    ADMIN_LOGIN_REQUEST : "ADMIN_LOGIN_REQUEST",
    ADMIN_LOGIN_SUCCESS : "ADMIN_LOGIN_SUCCESS",
    ADMIN_LOGIN_FAIL : "ADMIN_LOGIN_FAIL",
    ADMIN_LOGOUT : "ADMIN_LOGOUT",
    
    ADMIN_USER_FETCH_REQUEST : "ADMIN_USER_FETCH_REQUEST",
    ADMIN_USER_FETCH_SUCCESS : "ADMIN_USER_FETCH_SUCCESS",
    ADMIN_USER_FETCH_FAIL : "ADMIN_USER_FETCH_FAIL",
    
    ADMIN_BIKE_ADD_REQUEST : "ADMIN_BIKE_ADD_REQUEST",
    ADMIN_BIKE_ADD_SUCCESS : "ADMIN_BIKE_ADD_SUCCESS",
    ADMIN_BIKE_ADD_FAIL : "ADMIN_BIKE_ADD_FAIL",

    ADMIN_GET_BIKE_REQUEST :"ADMIN_GET_BIKE_REQUEST",
    ADMIN_GET_BIKE_FAIL : "ADMIN_GET_BIKE_FAIL",
    ADMIN_GET_BIKE_SUCCESS : "ADMIN_GET_BIKE_SUCCES",

    ADMIN_ADD_LOCATION_REQUEST : "ADMIN_ADD_LOCATION_REQUEST",
    ADMIN_ADD_LOCATION_SUCCESS : "ADMIN_ADD_LOCATION_SUCCESS",
    ADMIN_ADD_LOCATION_FAIL : "ADMIN_ADD_LOCATION_FAIL",

    ADMIN_DELETE_BIKE_REQUEST : "ADMIN_DELETE_BIKE_REQUEST",
    ADMIN_DELETE_BIKE_SUCCESS : "ADMIN_DELETE_BIKE_SUCCESS",
    ADMIN_DELETE_BIKE_FAIL : "ADMIN_DELETE_BIKE_FAIL",

    ADMIN_GET_LOCATION_REQUEST : "ADMIN_GET_LOCATION_REQUEST",
    ADMIN_GET_LOCATION_SUCCESS : "ADMIN_GET_LOCATION_SUCCESS",
    ADMIN_GET_LOCATION_FAIL : "ADMIN_GET_LOCATION_FAIL",

    ADMIN_EDIT_LOCATION_REQUEST : "ADMIN_EDIT_LOCATION_REQUEST",
    ADMIN_EDIT_LOCATION_SUCCESS : "ADMIN_EDIT_LOCATION_SUCCESS",
    ADMIN_EDIT_LOCATION_FAIL : "ADMIN_EDIT_LOCATION_FAIL",

    ADMIN_DELETE_LOCATION_REQUEST : "ADMIN_DELETE_LOCATION_REQUEST",
    ADMIN_DELETE_LOCATION_SUCCESS : "ADMIN_DELETE_LOCATION_SUCCESS",
    ADMIN_DELETE_LOCATION_FAIL : "ADMIN_DELETE_LOCATION_FAIL",
}