export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL"

export const USER_LOGOUT = "USER_LOGOUT"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const USER_PROFILE_REQUEST  = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS  = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL  = "USER_PROFILE_FAIL";

export const USER_IMAGE_REQUEST = "USER_IMAGE_REQUEST";
export const USER_IMAGE_SUCCESS = "USER_IMAGE_SUCCESS";
export const USER_IMAGE_FAIL = "USER_IMAGE_FAIL";