export const userActionType = {

    USER_SIGNUP_REQUEST: "USER_SIGNUP_REQUEST",
    USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
    USER_SIGNUP_FAIL: "USER_SIGNUP_FAIL",

    USER_LOGOUT: "USER_LOGOUT",

    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",

    GOOGLE_SIGNUP_REQUEST: "GOOGLE_SIGNUP_REQUEST",
    GOOGLE_SIGNUP_SUCCESS: "GOOGLE_SIGNUP_SUCCESS",
    GOOGLE_SIGNUP_FAIL: "GOOGLE_SIGNUP_FAIL",

    GET_USER_PROFILE_REQUEST: "  GET_USER_PROFILE_REQUEST",
    GET_USER_PROFILE_SUCCESS: " GET_USER_PROFILE_SUCCESS",
    GET_USER_PROFILE_FAIL: " GET_USER_PROFILE_FAIL",

    UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
    UPDATE_USER_PROFILE_DETAILS: "UPDATE_USER_PROFILE_DETAILS",

    USER_UPLOAD_IMAGE_REQUEST: "USER_UPLOAD_IMAGE_REQUEST",
    USER_UPLOAD_IMAGE_SUCCESS: "USER_UPLOAD_IMAGE_SUCCESS",
    USER_UPLOAD_IMAGE_FAIL: "USER_UPLOAD_IMAGE_FAIL",


    USER_UPLOAD_PROOF_REQUEST: "USER_UPLOAD_PROOF_REQUEST",
    USER_UPLOAD_PROOF_SUCCESS: "USER_UPLOAD_PROOF_SUCCESS",
    USER_UPLOAD_PROOF_FAIL: "USER_UPLOAD_PROOF_FAIL",



    USER_GET_BIKES_REQUEST: "USER_GET_BIKES_REQUEST",
    USER_GET_BIKES_SUCCESS: "USER_GET_BIKES_SUCCESS",
    USER_GET_BIKES_FAIL: "USER_GET_BIKES_FAIL",

    HOME_BIKE_REQUEST : "HOME_BIKE_REQUEST",
    HOME_BIKE_SUCCESS : "HOME_BIKE_SUCCESS",
    HOME_BIKE_FAIL : "HOME_BIKE_FAIL",

    USER_GET_SEARCH_BIKES_REQUEST: "USER_GET_SEARCH_BIKES_REQUEST",
    USER_GET_SEARCH_BIKES_SUCCESS: "USER_GET_SEARCH_BIKES_SUCCESS",
    USER_GET_SEARCH_BIKES_FAIL: "USER_GET_SEARCH_BIKES_FAIL",

    USER_GET_ALL_RENTED_BIKES_REQUEST: "USER_GET_ALL_RENTED_BIKES_REQUEST",
    USER_GET_ALL_RENTED_BIKES_SUCCESS: "USER_GET_ALL_RENTED_BIKES_SUCCESS",
    USER_GET_ALL_RENTED_BIKES_FAIL: "USER_GET_ALL_RENTED_BIKES_FAIL",

    USER_GET_ACCEPTED_BIKES_REQUEST: "USER_GET_ACCEPTED_BIKES_REQUEST",
    USER_GET_ACCEPTED_BIKES_SUCCESS: "USER_GET_ACCEPTED_BIKES_SUCCESS",
    USER_GET_ACCEPTED_BIKES_FAIL: "USER_GET_ACCEPTED_BIKES_FAIL",



    USER_GET_REJECTED_BIKES_REQUEST: "USER_GET_REJECTED_BIKES_REQUEST",
    USER_GET_REJECTED_BIKES_SUCCESS: "USER_GET_REJECTED_BIKES_SUCCESS",
    USER_GET_REJECTED_BIKES_FAIL: "USER_GET_REJECTED_BIKES_FAIL",

    USER_GET_PENDING_BIKES_REQUEST: "USER_GET_PENDING_BIKES_REQUEST",
    USER_GET_PENDING_BIKES_SUCCESS: "USER_GET_PENDING_BIKES_SUCCESS",
    USER_GET_PENDING_BIKES_FAIL: "USER_GET_PENDING_BIKES_FAIL",

    USER_GET_ALL_REQUEST: "USER_GET_ALL_REQUEST",

    USER_GET_LOCATION_REQUEST: "USER_GET_LOCATION_REQUEST",
    USER_GET_LOCATION_SUCCESS: "USER_GET_LOCATION_SUCCESS",
    USER_GET_LOCATION_FAIL: "USER_GET_LOCATION_FAIL",

    USER_BOOKING_BIKE_REQUEST: "USER_BOOKING_BIKE_REQUEST",
    USER_BOOKING_BIKE_SUCCESS: "USER_BOOKING_BIKE_SUCCESS",
    USER_BOOKING_BIKE_FAIL: "USER_BOOKING_BIKE_FAIL",

    USER_GET_BOOKED_BIKE_REQUEST: "USER_GET_BOOKED_BIKE_REQUEST",
    USER_GET_BOOKED_BIKE_SUCCESS: "USER_GET_BOOKED_BIKE_SUCCESS",
    USER_GET_BOOKED_BIKE_FAIL: "USER_GET_BOOKED_BIKE_FAIL",

    USER_CANCEL_BOOKED_BIKE_REQUEST :"USER_CANCEL_BOOKED_BIKE_REQUEST",
    USER_CANCEL_BOOKED_BIKE_SUCCESS :"USER_CANCEL_BOOKED_BIKE_SUCCESS",
    USER_CANCEL_BOOKED_BIKE_FAIL :"USER_CANCEL_BOOKED_BIKE_FAIL",

    USER_END_BOOKED_BIKE_SUCCESS :"USER_END_BOOKED_BIKE_SUCCESS",
    USER_END_BOOKED_BIKE_FAIL :"USER_END_BOOKED_BIKE_FAIL",

    USER_PAY_FINE_REQUEST :"USER_PAY_FINE_REQUEST",
    USER_PAY_FINE_SUCCESS :"USER_PAY_FINE_SUCCESS",
    USER_PAY_FINE_FAIL :"USER_PAY_FINE_FAIL",

    USER_FINE_PAYMENT_SUCCESS:"USER_FINE_PAYMENT_SUCCESS",
    USER_FINE_PAYMENT_FAIL:"USER_FINE_PAYMENT_FAIL",

    USER_GET_CONTACT_REQUEST: "USER_GET_CONTACT_REQUEST",
    USER_GET_CONTACT_SUCCESS: "USER_GET_CONTACT_SUCCESS",
    USER_GET_CONTACT_FAIL: "USER_GET_CONTACT_FAIL",

    USER_GET_COUPON_REQUEST: "USER_GET_COUPON_REQUEST",
    USER_GET_COUPON_SUCCESS: "USER_GET_COUPON_SUCCESS",
    USER_GET_COUPON_FAIL: "USER_GET_COUPON_FAIL",

    USER_CREATE_ORDER_REQUEST :"USER_CREATE_ORDER_REQUEST",
    USER_CREATE_ORDER_SUCCESS :"USER_CREATE_ORDER_SUCCESS",
    USER_CREATE_ORDER_FAIL :"USER_CREATE_ORDER_FAIL",

    USER_GET_WALLET_REQUEST : "USER_GET_WALLET_REQUEST",
    USER_GET_WALLET_SUCCESS : "USER_GET_WALLET_SUCCESS",
    USER_GET_WALLET_FAIL : "USER_GET_WALLET_FAIL",

    USER_WALLET_BOOKING_SUCCESS : "USER_WALLET_BOOKING_SUCCESS",

    GET_BRANDS_REQUEST : "GET_BRANDS_REQUEST",
    GET_BRANDS_SUCCESS : "GET_BRANDS_SUCCESS",
    GET_BRANDS_FAIL : "GET_BRANDS_FAIL",

    GET_BIKE_WITH_BRAND_REQUST:"GET_BIKE_WITH_BRAND_REQUST",
    GET_BIKE_WITH_BRAND_SUCCESS:"GET_BIKE_WITH_BRAND_SUCCESS",
    GET_BIKE_WITH_BRAND_FAIL:"GET_BIKE_WITH_BRAND_FAIL",
}

